spring.application.name=reportes-api
spring.data.mongodb.uri=mongodb+srv://libardojosevilleropaternina_db_user:bkQbw1G8uVS68Yph@reportes-urbanos.6cnuiga.mongodb.net/reportes_urbanos?retryWrites=true&w=majority
spring.data.mongodb.database=reportes_urbanos



